Created MaintainerCard component (and story)
AccessibleForAll/AccessibleWebDev pull request #172
Opened 2022-10-16 22:07 UTC by Gammarkin

## Describe your changes
Created MaintainerCard component, story, and made css for the component

## Screenshots - If Any (Optional)
![image](https://user-images.githubusercontent.com/92131987/196060534-44f31bed-c6b4-4c6a-80d3-27c9671caa38.png)

## Link to issue
Create MaintainerCard component (and story) #170

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.
- [ ] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.
the button with the gh user has a anchor that should take the user to the gh link of the person on the card.

2022-10-17 06:19 UTC, EmmaDawsonDev requested changes
Apologies for so many comments! This is looking good but there's a few changes I'd like to see before it can be merged. Let me know if anything seems unclear.

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.module.css
> +    margin-bottom: -5em;
Please stick to rem, not a mix of em and rem

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.module.css
> +    position: relative;
These should not be needed

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.module.css
> +    .maintainerContainer {
There should not be a need for any media queries on a card that should look the same on all screen sizes.

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.module.css
> +    font-size: 1.1rem;
```suggestion
    font-size: 1rem;
```

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.module.css
> +    font-size: 1.2rem;
```suggestion
    font-size: 1rem;
```

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.tsx
> +export interface MaintainerCardProps {
none of the props need to start with the word 'maintainer'. It is implied from the component.

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.tsx
> +				<h1 className={styles.maintainerFullName}>
h1 is not the right element to use here. I'd suggest that it's not a heading at all so a p tag with styling is more than adequate.

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.tsx
> +				<a href={maintainerGithubLink} target="_blank" rel="noreferrer">
A button nested inside a link is not good semantic html. This is a link to another site, therefore button should be removed and the link can be styled to look like a button instead.

2022-10-17 06:19 UTC, EmmaDawsonDev commented on components/MaintainerCard/MaintainerCard.tsx
> +				<a href={maintainerGithubLink} target="_blank" rel="noreferrer">
Also, please remove the target=_blank rel=noreferrer as links should not open in a new window/tab

2022-10-17 06:19 UTC, EmmaDawsonDev commented on stories/MaintainerCard.stories.tsx
> +}
I don't think this is needed. The data can be placed directly in the args below.

2022-10-17 06:19 UTC, EmmaDawsonDev commented on stories/MaintainerCard.stories.tsx
> +export const DesktopMaintainerCard = Template.bind({})
```suggestion
export const MaintainerCard = Template.bind({})
```

2022-10-17 18:00 UTC, Gammarkin commented
no problem! Thanks for the suggestions. Will work on it!

2022-10-22 05:13 UTC, ctoffanin requested changes

2022-10-22 05:13 UTC, ctoffanin commented on stories/MaintainerCard.stories.tsx
> +	<MaintainerCard {...args} />
This is not working. You renamed the component during import and the story is not showing up.

2022-10-22 05:13 UTC, ctoffanin commented on stories/MaintainerCard.stories.tsx
> +	<MaintainerCard {...args} />
My suggestion is to replace the content this file with this
```
import React from "react"
import { ComponentStory, ComponentMeta } from "@storybook/react"

import {
	MaintainerCard,
	MaintainerProps,
} from "../components/MaintainerCard/MaintainerCard"

export default {
	title: "Example/MaintainerCard",
	component: MaintainerCard,
} as ComponentMeta<typeof MaintainerCard>

const Template: ComponentStory<typeof MaintainerCard> = (args) => (
	<MaintainerCard {...args} />
)

export const DesktopMaintainerCard = Template.bind({})

DesktopMaintainerCard.args = {
	image:
		"https://img.freepik.com/free-photo/handsome-smiling-young-african-man_171337-9650.jpg",
	fullName: "John Doe",
	description:
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel tincidunt luctus, nunc nisl aliquam massa, eget aliquam nisl nisl eu nunc. Sed euismod, nisl vel tincidunt luctus, nunc nisl aliquam massa, eget aliquam nisl nisl eu nunc.",
	githubLink: "https://github.com",
} as MaintainerProps
```

To keep the original component's name and avoid confusion with naming.

2022-10-22 05:16 UTC, ctoffanin commented
Sorry for the delay. We had a crazy busy week.
Please check my comments and let me know if something is not clear, and I'll be back to you.

2022-10-22 19:33 UTC, ctoffanin approved these changes

2022-10-22 19:34 UTC, ctoffanin commented
Nice, thank you so much for contributing!

2022-10-22 19:34 UTC, merged