improve styling of Navigation and add searchbox
AccessibleForAll/AccessibleWebDev pull request #322
Opened 2023-06-12 15:52 UTC by DIWAKARKASHYAP

## Describe your changes

## Screenshots - If Any (Optional)

## Link to issue

Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.
- [ ] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

2023-06-12 17:50 UTC, EmmaDawsonDev requested changes
Hi @DIWAKARKASHYAP thank you for your keenness to contribute to this project. We normally do not accept PRs that do not have a linked issue (Rule 1 of the contributor guidelines). However, I understand that sometimes it's hard to follow when different repos have different rules so I will not take that into account this time. 

In this PR you have worked on two separate issues and since the search functionality is already assigned to someone else I request you to remove those parts of the changes you made and leave only the navigation styling changes for now. Please feel free to raise an issue for the navigation styling and I will assign it to you.

2023-06-12 17:50 UTC, EmmaDawsonDev commented on components/Nav/NavPrimary.module.css
> +  background-color: #28968C;
Please use the variable colors listed in the global css files.

2023-06-12 17:50 UTC, EmmaDawsonDev commented on components/Nav/NavPrimary.module.css
> +  background-color: #28968C;
Please use the variable colors listed in the global css file

2023-06-12 17:50 UTC, EmmaDawsonDev commented on components/Nav/NavPrimary.module.css
> +.searchBox{
Please remove this from the PR

2023-06-12 17:50 UTC, EmmaDawsonDev commented on components/Nav/NavPrimary.module.css
> +    width: 12rem;
Please leave the width as it was for now

2023-06-12 17:50 UTC, EmmaDawsonDev commented on components/Nav/NavPrimary.tsx
> +	const [search, setSearch] = useState<string>("")
Please remove all of the code to do with search

2023-06-13 04:00 UTC, DIWAKARKASHYAP commented
i am sorry and thankyou for your time and effort of reviewing

2023-06-19 04:53 UTC, DIWAKARKASHYAP commented
@EmmaDawsonDev please check

2023-06-23 16:21 UTC, EmmaDawsonDev requested changes
Thanks for removing the stuff related to search. There's just a few more adjustments to make before this is ready to be merged. In the globals.css file there is a class called active. The styles there need to be updated to match the new design too.

2023-06-23 16:21 UTC, EmmaDawsonDev commented on components/Nav/NavPrimary.module.css
> +  padding: 4px;
This padding feels too tight, I think maybe 8px would be more appropriate.

2023-06-23 16:21 UTC, EmmaDawsonDev commented on components/Nav/NavPrimary.module.css
> +  color: var(--white);
Setting the text to white means the color contrast on dark mode doesn't work. Please use the --text variable instead. Please also switch the background color back to primaryLt

2023-07-02 13:38 UTC, EmmaDawsonDev commented
Hi @DIWAKARKASHYAP I'm not sure what's going on here or why you've deleted the primaryNav file. I am just waiting on you to adjust the .active class in the global.css file, as mentioned in one of my earlier comments. Let me know if you need any help.

2023-07-02 14:34 UTC, DIWAKARKASHYAP commented
@EmmaDawsonDev apology i think if i delete then only changes gonna delete 
how can i restore this branch to previous commit , is this possible ?

2023-07-02 14:37 UTC, EmmaDawsonDev commented
No problem, I wanted to check as I thought it was probably a mistake. You can use `git revert #commit` where #commit is the string of numbers and letters given to the commit. You can find it here on GitHub or by typing git log in the terminal

2023-07-02 15:53 UTC, DIWAKARKASHYAP commented
@EmmaDawsonDev  thankyou soo much for help me ,
now i think its working perfectly

2023-07-02 17:59 UTC, EmmaDawsonDev approved these changes
Thanks for your help @DIWAKARKASHYAP and here's an article about good commit messages 😉 [Commit Messages](https://blog.ossph.org/how-to-write-a-good-git-commit-message/#:~:text=To%20set%20up%20a%20Git,t%20meet%20the%20specified%20format.)

2023-07-02 17:59 UTC, merged