feat: add Touch Target Minimum section to Links and Button pages
AccessibleForAll/AccessibleWebDev pull request #390
Opened 2024-01-12 23:26 UTC by CBID2

## Describe your changes
This PR adds a Touch Target Minimum section to the Links and Buttons pages, helping developers gain a better understanding of how to make these components more accessible.
## Screenshots - If Any (Optional)

## Link to issue

Closes #386 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.
- [ ] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
It is still a work in progress.

2024-01-13 00:41 UTC, CBID2 commented
Hi @EmmaDawsonDev! :) I'm done with my PR.

2024-01-14 19:05 UTC, EmmaDawsonDev requested changes
Thanks Chrissy. I left a few comments. Let me know if you need help with anything.

2024-01-14 19:05 UTC, EmmaDawsonDev commented on components/ContentTemplates/ButtonsTemplate.tsx
> +				sectionName="Touch Target Minimum"
```suggestion
				sectionName="touchTargetMinimum"
```

2024-01-14 19:05 UTC, EmmaDawsonDev commented on components/ContentTemplates/ButtonsTemplate.tsx
> +				</ul>
There's no need for this to be a list. Please rewrite as just a paragraph.

2024-01-14 19:05 UTC, EmmaDawsonDev commented on components/ContentTemplates/ButtonsTemplate.tsx
> +				</p>
Links are already included in a section at the bottom of the page so this can be removed

2024-01-14 19:05 UTC, EmmaDawsonDev commented on components/ContentTemplates/LinksTemplate.tsx
> +					sectionName="Touch Target Minimum"
Same comments apply to this one as for buttons

2024-01-14 19:05 UTC, EmmaDawsonDev commented on data/pageNavigationLists.ts
> +	{ linkName: "Touch Target Minimum", href: "#touchTargetMinimum" },
Please add the link object in the correct place in the list corresponding to where it appears on the page.

Please also add it to the buttonPageNavigation array.

2024-01-27 23:01 UTC, closed without merging

2024-01-27 23:37 UTC, CBID2 commented
Hi @EmmaDawsonDev! :) Too many issues occured in the revision of this PR, so I closed. The improved version in is PR #391.