Issue 27 add modeltemplate component
AccessibleForAll/AccessibleWebDev pull request #65
Opened 2022-10-02 02:51 UTC by muditchoudhary

Close: #27 

Changes made:

1. Added ModalTemplate.tsx fle
2. Import & add the ModalTemplate in Layout tag 
3. Add ModalTemplate to the config file.

2022-10-02 08:44 UTC, EmmaDawsonDev requested changes
Just a small copy-paste mistake to fix in the component then this is ready to merge :)

2022-10-02 08:44 UTC, EmmaDawsonDev commented on components/ContentTemplates/ModalsTemplate.tsx
> +	return <div>MenusTemplate</div>
```suggestion
	return <div>ModalsTemplate</div>
```

2022-10-03 04:17 UTC, muditchoudhary commented
@EmmaDawsonDev fixed!! see it's good :)

2022-10-03 16:29 UTC, EmmaDawsonDev approved these changes
Looks great, thank you!

2022-10-03 16:30 UTC, merged