Updated and Added More Issue Templates
AccessibleForAll/AccessibleWebDev pull request #76
Opened 2022-10-03 07:47 UTC by MrKrishnaAgarwal

## Describe your changes

I have Updated and Added More Issue Templates, and converted .md to .yml with better choices

## Screenshots - If Any (Optional)

![image](https://user-images.githubusercontent.com/100597998/193525884-17582b96-7bd1-42dc-96c6-293f40ddf2af.png)
![image](https://user-images.githubusercontent.com/100597998/193525923-7232f4b8-8728-4f6b-9957-c4c6576d7cad.png)
![image](https://user-images.githubusercontent.com/100597998/193525966-a54ba588-255f-48bf-a200-ac7fdc55f5be.png)

## Issue ticket number and link - If Any

Closes #75 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)

cc @EmmaDawsonDev

2022-10-04 14:12 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +  - type: input
This one can be removed.

2022-10-04 14:26 UTC, EmmaDawsonDev requested changes
There's just a few updates to make these easier to use for people. Mostly I don't think we need so many questions and most of them don't need to be required. Let me know if you have any questions.

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +      required: true
This whole section can be removed, it's always going to affect the same URL

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +      required: true
Remove the required here, it's not always possible to provide reproduction steps

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +      placeholder: Short and explicit description of your incident...
```suggestion
      placeholder: Detailed description of your issue...
```

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +      description: Please enter an explicit description of your issue
```suggestion
      description: Please enter a detailed description of your issue
```

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +      required: true
```suggestion
  
```

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +      description: Please enter an explicit description of your issue
```suggestion
      description: Please enter the steps you took when the issue happened
```

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +        - Mac
Can we also add iOS, android and other to this section?

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
> +      required: false
Remove these three inputs.

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
> +      required: true
```suggestion
      required: false
```

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
> +      required: false
Remove these ones

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/OTHER.yml
> +title: Other <subject>
```suggestion
title: [OTHER] <subject>
```

Let's use the same format for all templates

2022-10-04 14:26 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +      description: What is the impacted environment ?
```suggestion
      description: What is the impacted operating system?
```

2022-10-04 14:48 UTC, MrKrishnaAgarwal commented
@EmmaDawsonDev I have made all the Required Changes

2022-10-05 09:13 UTC, EmmaDawsonDev reviewed
There seems to be a couple of issues with the syntax now, probably just some wrong indentation somewhere.

2022-10-05 09:13 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/BUG-REPORT.yml
> +  - type: textarea
I think there's something slightly wrong with the formatting. I'm seeing the following error when I try to view the file:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/57045550/194024373-215105dc-919f-4e4d-8a76-68482c5c8bc7.png">

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms

2022-10-05 09:13 UTC, EmmaDawsonDev commented on .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
> +      required: false
Remove Drawbacks and unresolved questions too please

2022-10-05 09:14 UTC, EmmaDawsonDev requested changes
Changes requested in previous comment (forgot to check correct option)

2022-10-06 03:58 UTC, closed without merging