added_breadcrumbs_template
AccessibleForAll/AccessibleWebDev pull request #79
Opened 2022-10-04 06:26 UTC by gaurav-iitb

## Describe your changes

## Screenshots - If Any (Optional)

## Issue ticket number and link - If Any

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Any additional information that you want to give us.

2022-10-04 14:27 UTC, EmmaDawsonDev commented on pages/[content].tsx
> +import Breadcrumbs from "../components/ContentTemplates/BreadcrumbsTemplate"
Can you import this one in the correct place alphabetically?

2022-10-04 14:28 UTC, EmmaDawsonDev requested changes
Just a small change then this looks ready to merge :)

2022-10-04 18:38 UTC, gaurav-iitb commented
I have done changes now. please merge it

2022-10-05 09:16 UTC, EmmaDawsonDev approved these changes
Great! Thanks for your contribution!

2022-10-05 09:16 UTC, merged