Footer
AccessibleForAll/AccessibleWebDev pull request #81
Opened 2022-10-04 06:44 UTC by yashfalke77

## Describe your changes
Hey @EmmaDawsonDev  I added the footer , do checkout if any changes are needed do tag me :)
## Screenshots - If Any (Optional)
![image](https://user-images.githubusercontent.com/82655175/193751630-27a63725-4a9f-4e2f-b292-01bc90889d11.png)

## Issue ticket number and link - If Any
Issue No: #19 

## Additional Information (Optional)
This Time I didn't committed the package-lock and yarn lock

2022-10-04 14:50 UTC, EmmaDawsonDev requested changes
Hi Yash, there are a small number of changes to make and then this will be ready to merge. Let me know if you have any questions.

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +		<div className={styles.footer}>
```suggestion
		<footer className={styles.footer}>
```

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +		</div>
```suggestion
		</footer>
```

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +							rel="noreferrer"
remove these two please. To be accessible links should not open in a new browser

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +							rel="noreferrer"
Remove these two please

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +					style={{ paddingInlineStart: "0px" }}>
Please remove these inline styles and use classes instead

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +						<Link href="/about">
This link doesn't exist and will cause a 404

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +						<Link href="/about">
Link doesn't exist

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +						<svg
React icons is installed in the project. Please use an icon from here instead: https://react-icons.github.io/react-icons/search?q=github

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +						rel="noreferrer">
Remove these two so the link opens in the same window

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +						href="https://github.com/AccessibleForAll"
```suggestion
						href="https://github.com/AccessibleForAll"
						aria-label="Github - Accessible For All"
```

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/footer.module.css
> +    margin-bottom: 0rem;
```suggestion
    margin-bottom: 0rem;
    padding: 0;
```

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +					<li className={styles.footer__linkName}>Community</li>
The list heading should come before the list and use a h2 tag, same for both.

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +				<span className={styles.footer__copyrightText}>
```suggestion
				<p className={styles.footer__copyrightText}>
```

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +				</span>
```suggestion
				</p>
```

2022-10-04 14:50 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +					<b className={styles.footer__copyrightTextName}>Accessible For All</b>
```suggestion
					<strong className={styles.footer__copyrightTextName}>Accessible For All</strong>
```

2022-10-04 15:20 UTC, yashfalke77 commented
Hey @EmmaDawsonDev made the recommended fixes

2022-10-05 09:25 UTC, EmmaDawsonDev requested changes
thanks for your updates. There's just a couple of links and the github icon which didn't get updated then this looks good to merge.

2022-10-05 09:25 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +							<Link href="/about">
Please just redirect to the homepage for now since there is no about page and it throws a 404.

2022-10-05 09:25 UTC, EmmaDawsonDev commented on components/Footer/Footer.tsx
> +							<Link href="/about">
This one can also redirect to the homepage for now
```suggestion
							<Link href="/">
```

2022-10-05 14:03 UTC, yashfalke77 commented
@EmmaDawsonDev  what are changes about github icon , rest changes are made

2022-10-05 14:12 UTC, EmmaDawsonDev commented
> @EmmaDawsonDev what are changes about github icon , rest changes are made

React Icons is installed already in the project so instead of using an svg you can do
```import {BsGithub } from "react-icons/bs"```

and
```<BsGithub color="white" size="1rem" aria-label="Github" />``` (change the size to whatever is appropriate)

2022-10-05 18:39 UTC, EmmaDawsonDev commented
Thank you so much, this looks great!

2022-10-05 18:39 UTC, EmmaDawsonDev approved these changes

2022-10-05 18:39 UTC, merged